sudo: required
service:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 ## disable GCP SDK prompts

before_install:
  - openssl aes-256-cbc -K $encrypted_3e4bc7cafeed_key -iv $encrypted_3e4bc7cafeed_iv -in gcp-service-account.json.enc -out gcp-service-account.json -d ##Decrypt the gcp-service-account.json.enc
  - curl https://sdk.cloud.google.com > install.sh  ## download gcp sdk
  - bash install.sh --disable-prompts  ## install gcp sdk
  #- gcloud components update kubectl ## update kubectl
  - gcloud auth activate-service-account --key-file=gcp-service-account.json ## activate service account to allow gcp sdk to administer k8s cluster
  ### - install travis CI CLI locally to encrypt the service account key file "gcp-service-account.json"
  ### - travis login
  ### - travis encrypt-file  gcp-service-account.json -r OmkarG1986/multi-k8s
  - gcloud config set project multi-k8s-269907
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials  checkpoint-multi-cluster	##gcloud container clusters get-credentials updates a kubeconfig file with appropriate credentials and endpoint information to point kubectl at a specific cluster in Google Kubernetes Engine.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t omkarsonawane/docker-multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=tru omkarsonawane/docker-multo-client-test npm run test


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
